from . import TeethSeg
from . import ACDC
from . import AMOS
from . import BBBC
from . import BRATS
from . import BUS
from . import BrainDevelopment
from . import BrainMetShare
from . import CHAOS
from . import COCA
from . import CannabisT1
from . import CheXplanation
from . import CoNSeP
from . import DDR
from . import DRIVE
from . import EOphtha
from . import EchoNet
from . import FLARE
from . import FeTA
from . import Feto_Plac
from . import I2CVB
from . import IDRID
from . import ISBI
from . import ISBI_EM
from . import ISLES
from . import KiTS
from . import LGGFlair
from . import LITS
from . import LUNA
from . import MNMS
from . import MSD
from . import OASIS
from . import OCTA500
from . import PROMISE12
from . import PanDental
from . import PanNuke
from . import ROSE
from . import SCD
from . import SMIR
from . import STARE
from . import SegTHOR
from . import SpineWeb
from . import Synapse_Abdomen
from . import T1mix
from . import TUCC
from . import VerSe
from . import WBC
from . import WMH
from . import WORD