paths = {
    "ROOT": "/home/vib9/src/MegaMedical"
}

dataset_registry = {
    "TeethSeg": "",
    "ACDC": "megamedical.ACDC.process_assets",
    "AMOS": "megamedical.AMOS.process_assets",
    "BBBC": "megamedical.BBBC.process_assets",
    "BRATS": "megamedical.BRATS.process_assets",
    "BUS": "megamedical.BUS.process_assets",
    "BrainDevelopment": "megamedical.BrainDevelopment.process_assets",
    "BrainMetShare": "megamedical.BrainMetShare.process_assets",
    "CHAOS": "megamedical.CHAOS.process_assets",
    "COCA": "megamedical.COCA.process_assets",
    "CannabisT1": "megamedical.CannabisT1.process_assets",
    "CheXplanation": "megamedical.CheXplanation.process_assets",
    "CoNSeP": "megamedical.CoNSeP.process_assets",
    "DDR": "megamedical.DDR.process_assets",
    "DRIVE": "megamedical.DRIVE.process_assets",
    "EOphtha": "megamedical.EOphtha.process_assets",
    "EchoNet": "megamedical.EchoNet.process_assets",
    "FLARE": "megamedical.FLARE.process_assets",
    "FeTA": "megamedical.FeTA.process_assets",
    "Feto_Plac": "megamedical.Feto_Plac.process_assets",
    "I2CVB": "megamedical.I2CVB.process_assets",
    "IDRID": "megamedical.IDRID.process_assets",
    "ISBI": "megamedical.ISBI.process_assets",
    "ISBI_EM": "megamedical.ISBI_EM.process_assets",
    "ISLES": "megamedical.ISLES.process_assets",
    "KiTS": "megamedical.KiTS.process_assets",
    "LGGFlair": "megamedical.LGGFlair.process_assets",
    "LITS": "megamedical.LITS.process_assets",
    "LUNA": "megamedical.LUNA.process_assets",
    "MNMS": "megamedical.MNMS.process_assets",
    "MSD": "megamedical.MSD.process_assets",
    "OASIS": "megamedical.OASIS.process_assets",
    "OCTA500": "megamedical.OCTA500.process_assets",
    "PROMISE12": "megamedical.PROMISE12.process_assets",
    "PanDental": "megamedical.PanDental.process_assets",
    "PanNuke": "megamedical.PanNuke.process_assets",
    "ROSE": "megamedical.ROSE.process_assets",
    "SCD": "megamedical.SCD.process_assets",
    "SMIR": "megamedical.SMIR.process_assets",
    "STARE": "megamedical.STARE.process_assets",
    "SegTHOR": "megamedical.SegTHOR.process_assets",
    "SpineWeb": "megamedical.SpineWeb.process_assets",
    "Synapse_Abdomen": "megamedical.Synapse_Abdomen.process_assets",
    "T1mix": "megamedical.T1mix.process_assets",
    "TUCC": "megamedical.TUCC.process_assets",
    "VerSe": "megamedical.VerSe.process_assets",
    "WBC": "megamedical.WBC.process_assets",
    "WMH": "megamedical.WMH.process_assets",
    "WORD": "megamedical.WORD.process_assets",
}