paths = {
    "ROOT": "/home/vib9/src/MegaMedical"
}

dataset_registry = {
    "TeethSeg": "",
    "ACDC": "megamedical.ACDC.process_assets",
    "AMOS": "",
    "BBBC": "",
    "BRATS": "",
    "BUS": "",
    "BrainDevelopment": "",
    "BrainMetShare": "",
    "CHAOS": "",
    "COCA": "",
    "CannabisT1": "",
    "CheXplanation": "",
    "CoNSeP": "",
    "DDR": "",
    "DRIVE": "",
    "EOphtha": "",
    "EchoNet": "",
    "FLARE": "",
    "FeTA": "",
    "Feto_Plac": "",
    "I2CVB": "",
    "IDRID": "",
    "ISBI": "",
    "ISBI_EM": "",
    "ISLES": "",
    "KiTS": "",
    "LGGFlair": "",
    "LITS": "",
    "LUNA": "",
    "MNMS": "",
    "MSD": "",
    "OASIS": "",
    "OCTA500": "",
    "PROMISE12": "",
    "PanDental": "",
    "PanNuke": "",
    "ROSE": "",
    "SCD": "",
    "SMIR": "",
    "STARE": "",
    "SegTHOR": "",
    "SpineWeb": "",
    "Synapse_Abdomen": "",
    "T1mix": "",
    "TUCC": "",
    "VerSe": "",
    "WBC": "",
    "WMH": "",
    "WORD": "",
}